openapi: 3.0.3
info:
  title: GNIV - OpenAPI 3.0
  description: |-
    APIs for GNIV Power App
  contact:
    email: artiwarahd@gmail.com
  version: 0.0.1
servers:
  - url: http://xx.xxx.xxx.xx/api/v1
tags:
  - name: category
    description: All About Categories
  - name: product
    description: All About Products
  # - name: product_variation
  #   description: All About Product Variations
  - name: order
    description: CRUD Orders
  - name: promotion
    description: All About Promotions
paths:
  /categories:
    get:
      tags:
        - category
      summary: List Categories
      description: returns all categories
      operationId: listCategory
      security:
        - api_key:
            - read:categories
  /products:
    get:
      tags:
        - product
      summary: List Products
      description: returns all products
      operationId: listProduct
      security:
        - api_key:
            - read:products
  /products/search:
    get:
      tags:
        - product
      summary: Search Products
      description: Search products by specific fields with values
      operationId: searchProducts
      security:
        - api_key:
            - write:products
            - read:products
  # /product:
    # post:
    #   tags:
    #     - product
    #   summary: Add a new product to the store
    #   description: Add a new product to the store
    #   operationId: addProduct
    #   requestBody:
    #     description: Create a new product in the store
    #     content:
    #       application/json:
    #         schema:
    #           $ref: '#/components/schemas/Product'
    #       application/x-www-form-urlencoded:
    #         schema:
    #           $ref: '#/components/schemas/Product'
    #     required: true
    #   responses:
    #     '200':
    #       description: Successful operation
    #       content:
    #         application/json:
    #           schema:
    #             $ref: '#/components/schemas/Product'
    #     '405':
    #       description: Invalid input
    #   security:
    #     - api_key:
    #         - write:products
    #         - read:products
  /product/{productId}:
    get:
      tags:
        - product
      summary: Find product by ID
      description: Returns a single product
      operationId: getProductById
      security:
        - api_key: []
        - api_key:
            - write:products
            - read:products
    # put:
    #   tags:
    #     - product
    #   summary: Update an existing product
    #   description: Update an existing product by Id
    #   operationId: updateProduct
    #   requestBody:
    #     description: Update an existent product in the store
    #     content:
    #       application/json:
    #         schema:
    #           $ref: '#/components/schemas/Product'
    #       application/x-www-form-urlencoded:
    #         schema:
    #           $ref: '#/components/schemas/Product'
    #     required: true
    #   responses:
    #     '200':
    #       description: Successful operation
    #       content:
    #         application/json:
    #           schema:
    #             $ref: '#/components/schemas/Product'
    #     '400':
    #       description: Invalid ID supplied
    #     '404':
    #       description: Product not found
    #     '405':
    #       description: Validation exception
    #   security:
    #     - api_key:
    #         - write:products
    #         - read:products
    # delete:
    #   tags:
    #     - product
    #   summary: Deletes a product
    #   description: delete a product
    #   operationId: deleteProduct
    #   parameters:
    #     - name: api_key
    #       in: header
    #       description: ''
    #       required: false
    #       schema:
    #         type: string
    #     - name: productId
    #       in: path
    #       description: Product id to delete
    #       required: true
    #       schema:
    #         type: integer
    #         format: int64
    #   responses:
    #     '400':
    #       description: Invalid product value
    #   security:
    #     - api_key:
    #         - write:products
    #         - read:products
  /orders:
    get:
      tags:
        - order
      summary: List Order
      description: returns all orders
      operationId: listOrder
      security:
        - api_key:
            - read:orders
  /order:
    post:
      tags:
        - order
      summary: Open a new order
      description: Open a new order, ready to add sold product info
      operationId: addOrder
      security:
        - api_key:
            - write:orders
            - read:orders
  /order/{orderId}:
    get:
      tags:
        - order
      summary: Find order by ID
      description: Returns a single order
      operationId: getOrderById
      security:
        - api_key: []
        - api_key:
            - write:orders
            - read:orders
    put:
      tags:
        - order
      summary: Update an existing order
      description: Update an existing order by Id
      operationId: updateOrder
      security:
        - api_key:
            - write:orders
            - read:orders
  /order/{orderId}/delete_item/{orderItemId}:
    delete:
      tags:
        - order
      summary: Delete item from the order
      description: ''
      operationId: deleteItemOrder
      security:
        - api_key:
            - write:orders
            - read:orders
  /order/{orderId}/submit:
    post:
      tags:
        - order
      summary: Submit the order
      description: ''
      operationId: submitOrder
      security:
        - api_key:
            - write:orders
            - read:orders
  /order/{orderId}/cancel_order:
    post:
      tags:
        - order
      summary: Cancel the order
      description: ''
      operationId: cancelOrder
      security:
        - api_key:
            - write:orders
            - read:orders
  /order/{orderId}/upload_bill_photo:
    post:
      tags:
        - order
      summary: Upload bill photo
      description: ''
      operationId: uploadBillPhoto
      security:
        - api_key:
            - write:orders
            - read:orders
  /promotions:
    get:
      tags:
        - promotion
      summary: List Promotions
      description: returns all promotions
      operationId: listPromotion
      security:
        - api_key:
            - read:promotions
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: header